### ISSUE TITLE
Auto-Input and Factory Upgrades not checking inventories 1.18.2

### ISSUE THREAD

**Issue by Staegrin** [Wilyicaro/BetterFurnacesReforged#43]
Version
BetterFurnacesReforged-1.18.2-1.2.3 & Ultimate-Furnaces-BFR-1.18.2-1.0
Forge 40.1.52
Minecraft 1.18.2
Neither the furnaces or the forges equipped with an Auto-Input or Factory Upgrade will auto pull smelt-able items from inventories. Until an item is modified in the furnace/forge.
![2022-07-01_01 25 27](https://user-images.githubusercontent.com/8494635/176794645-923460c8-2f5e-46e7-ab58-1e23209988da.png)
A furnace/Forge will only pull from the adjacent inventory if first an item is hoppered in or placed in manually. When the fuel slot has space, the fuel will be extracted automatically. Anything that can be smelted will not be detected until something changes inside the furnace/forge.
![2022-07-01_01 30 17](https://user-images.githubusercontent.com/8494635/176795010-f77b51df-4a0a-4f45-8670-35726878ebd5.png)
 The factory upgrade is set to Auto Input true, for the correct side and Redstone Ignored
![2022-07-01_01 31 38](https://user-images.githubusercontent.com/8494635/176795121-5bd7238d-d77c-434d-a7f9-d400f9ebc124.png)
3 stacks of copper dust not being extracted.
![2022-07-01_01 32 28](https://user-images.githubusercontent.com/8494635/176795193-ff96b198-04e1-4610-8768-30ce12339725.png)
![2022-07-01_01 32 29](https://user-images.githubusercontent.com/8494635/176795201-d295c443-072d-4ae8-b27c-b892d6ab1540.png)
Put in one dust into the top slot or remove some of the fuel and suddenly the furnace/forge will start to extract from the inventory next to it.

**Comment by Wilyicaro** [comment]
Have you tried using the newest version(1.18.2-1.2.4)? Soon I will analyze to find a solution for this bug

**Comment by Wilyicaro** [comment]
Sorry, but I did exactly the same block setup as you did, and the same factory upgrade configuration, and I didn't find this bug, maybe I fixed it in this new version and don't remember.

**Comment by Staegrin** [comment]
Using latest 
Ultimate-Furnaces-BFR-1.18.2-1.0.1
BetterFurnacesReforged-1.18.2-1.2.5
Still happening. Inventory of the furnace needs to be changed in some way before the inventory next to it gets checked.
In your setup, did you wait for the fuel to fill up? Before adding smeltable items into the inventory next to the furnace? Because the furnace will detect and extract fuel from an adjacent inventory without any problem. 
This filling up on fuel will also make the furnace check for smeltable items. When the fuel is full and nothing further changes it will stop checking adjacent inventories.

**Comment by Wilyicaro** [comment]
The furnace was already fueled and idle, with no inventory changes, and auto-input was working normally

**Comment by Staegrin** [comment]
Just tried in a world with only 
Ultimate-Furnaces-BFR-1.18.2-1.0.1
BetterFurnacesReforged-1.18.2-1.2.5 
jei-1.18.2-9.7.0.196
Fueled up
![2022-07-01_22 31 48](https://user-images.githubusercontent.com/8494635/176964624-262b1b6a-9ab2-4c86-b1ea-66650ce087e0.png)
Raw iron in the barrel
![2022-07-01_22 31 52](https://user-images.githubusercontent.com/8494635/176964705-fa4ef5b9-c82f-4755-909b-91bd9a3fec31.png)

![2022-07-01_22 31 54](https://user-images.githubusercontent.com/8494635/176964745-af0d0172-88d0-4eb0-8207-a8caf9828ace.png)
Put in one Raw iron
![2022-07-01_22 32 11](https://user-images.githubusercontent.com/8494635/176964771-6824f1cf-e529-40b4-8ba7-8a1e24da9bf3.png)
Now suddenly it notices all the other raw iron and starts extracting from the barrel
![2022-07-01_22 32 12](https://user-images.githubusercontent.com/8494635/176964882-b0beb892-4577-4cbe-8b79-e5da9b33687d.png)

**Comment by Wilyicaro** [comment]
https://user-images.githubusercontent.com/81383021/176969301-f5e70628-cbbc-429f-b753-3fd27a5af537.mp4

**Comment by Staegrin** [comment]
Just tested it. It works if the fuel is not full. In your case 37 coal. Then the automation works. As soon as there are 64 coal, it no longer detects smeltable items in the adjacent inventory.

**Comment by Wilyicaro** [comment]
It has 37 coals because before they were consumed when starting the auto-input they had 64 coals 😒

**Comment by Staegrin** [comment]
Same with the Fuel Liquid upgrade 
![2022-07-01_23 33 59](https://user-images.githubusercontent.com/8494635/176970500-f82e6b87-09b5-421c-be9b-f57d783bbfbc.png)
![2022-07-01_23 34 08](https://user-images.githubusercontent.com/8494635/176970520-0d47d5e8-f54a-4e56-b164-9eaffd7fc95d.png)
Plenty of lava in the tank and iron dust in the adjacent inventory
![2022-07-01_23 34 15](https://user-images.githubusercontent.com/8494635/176970575-15c0ef0b-92d8-4b53-8455-885b7ab59748.png)
Remove the full lava bucket, add some Iron dust into the adjacent inventory and now the Ultimate Forge can detect smeltable items and import them.

**Comment by Staegrin** [comment]
Some for some reason the fuel slot being full of fuel stops the upgrade from checking if smeltable material gets added to adjacent inventories.

**Comment by Wilyicaro** [comment]
Thanks for reporting this bug, I already found the problem, and I'll post the fix soon.

**Comment by Staegrin** [comment]
My pleasure. It was a strange edge case.

**Comment by Wilyicaro** [comment]
Fixed in version 1.18.2-1.2.6

**Comment by Staegrin** [comment]
Seems fully fixed. Thanks for the hard work.

**Comment by Wilyicaro** [comment]
My pleasure to make the fix ;)
