### ISSUE TITLE
Xp tank crash game again (or still?) 1.19.2

### ISSUE THREAD

**Issue by adamkad1** [Wilyicaro/BetterFurnacesReforged#60]
I saw a closed issue where you said its fixed, but my game still crashed when i slotted an xp tank upgrade into a ultimate forge

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2022-10-08 04:58:22
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
	at it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap$MapIterator.nextEntry(Object2IntOpenHashMap.java:755) ~[fastutil-8.5.6.jar%23127!/:?] {}
	at it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap$EntryIterator.next(Object2IntOpenHashMap.java:853) ~[fastutil-8.5.6.jar%23127!/:?] {}
	at it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap$EntryIterator.next(Object2IntOpenHashMap.java:847) ~[fastutil-8.5.6.jar%23127!/:?] {}
	at wily.betterfurnaces.blockentity.AbstractSmeltingBlockEntity.grantStoredRecipeExperience(AbstractSmeltingBlockEntity.java:1085) ~[BetterFurnacesReforged-1.19.2-1.0.2.jar%23160!/:1.19.2-1.0.2] {re:classloading}
	at wily.betterfurnaces.blockentity.AbstractSmeltingBlockEntity.tick(AbstractSmeltingBlockEntity.java:424) ~[BetterFurnacesReforged-1.19.2-1.0.2.jar%23160!/:1.19.2-1.0.2] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:pmmo.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap$MapIterator.nextEntry(Object2IntOpenHashMap.java:755) ~[fastutil-8.5.6.jar%23127!/:?] {}
	at it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap$EntryIterator.next(Object2IntOpenHashMap.java:853) ~[fastutil-8.5.6.jar%23127!/:?] {}
	at it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap$EntryIterator.next(Object2IntOpenHashMap.java:847) ~[fastutil-8.5.6.jar%23127!/:?] {}
	at wily.betterfurnaces.blockentity.AbstractSmeltingBlockEntity.grantStoredRecipeExperience(AbstractSmeltingBlockEntity.java:1085) ~[BetterFurnacesReforged-1.19.2-1.0.2.jar%23160!/:1.19.2-1.0.2] {re:classloading}
	at wily.betterfurnaces.blockentity.AbstractSmeltingBlockEntity.tick(AbstractSmeltingBlockEntity.java:424) ~[BetterFurnacesReforged-1.19.2-1.0.2.jar%23160!/:1.19.2-1.0.2] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:pmmo.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
-- Block entity being ticked --
Details:
	Name: ultimatefurnaces_bfr:ultimate_forge // wily.ultimatefurnaces.blockentity.UltimateForgeBlockEntity
	Block: Block{ultimatefurnaces_bfr:ultimate_forge}[colored=false,facing=up,lit=true,show_orientation=false,waterlogged=false]
	Block location: World: (-12,111,31), Section: (at 4,15,15 in -1,6,1; chunk contains blocks -16,-64,16 to -1,319,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Block: Block{ultimatefurnaces_bfr:ultimate_forge}[colored=false,facing=up,lit=true,show_orientation=false,waterlogged=false]
	Block location: World: (-12,111,31), Section: (at 4,15,15 in -1,6,1; chunk contains blocks -16,-64,16 to -1,319,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
Stacktrace:
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:pmmo.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,106,8), Section: (at 8,10,8 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1865133 game time, 2245970 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 46135 (now: false), thunder time: 22276 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 429115008 bytes (409 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 2700X Eight-Core Processor         
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Radeon RX 580 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=30.0.13023.4001
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 28625.81
	Virtual memory used (MB): 20131.27
	Swap memory total (MB): 12288.00
	Swap memory used (MB): 388.58
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:trashslot (incompatible), mod:jei (incompatible), mod:attributefix (incompatible), mod:projecte, mod:sophisticatedcore (incompatible), mod:clumps (incompatible), mod:journeymap (incompatible), mod:cookingforblockheads (incompatible), mod:controlling (incompatible), mod:comforts, mod:farmingforblockheads (incompatible), mod:bookshelf (incompatible), mod:sophisticatedbackpacks (incompatible), mod:balm (incompatible), mod:jeresources (incompatible), mod:cloth_config (incompatible), mod:forge, mod:supplementaries (incompatible), mod:mcwbridges, mod:farmersdelight (incompatible), mod:torchmaster (incompatible), mod:libipn (incompatible), mod:enchdesc (incompatible), mod:swingthroughgrass (incompatible), mod:moonlight (incompatible), mod:mousetweaks, mod:titanium (incompatible), mod:jade (incompatible), mod:mcwfences, mod:spectrelib (incompatible), mod:corail_dt, mod:ferroustry (incompatible), mod:domum_ornamentum, mod:corail_woodcutter_extension_byg, mod:patchouli (incompatible), mod:corail_woodcutter, mod:blockui, mod:croptopia (incompatible), mod:autoreglib (incompatible), mod:quark (incompatible), mod:elevatorid (incompatible), mod:inventoryhud, mod:tombstone, mod:structurize, mod:multipiston, mod:projectextended, mod:minecolonies (incompatible), mod:inventoryprofilesnext (incompatible), mod:cfm (incompatible), mod:appleskin, mod:functionalstorage (incompatible), mod:aquaculture, mod:corail_backpack, mod:fastleafdecay, mod:corail_pillar, mod:cyclic (incompatible), mod:xpbook, Supplementaries Generated Pack, mod:squatgrow (incompatible), mod:configured (incompatible), mod:exnihilosequentia, mod:bedrockminer, mod:bedbenefits (incompatible), mod:bedspreads, mod:easier_sleeping, mod:pmmo (incompatible), mod:architectury (incompatible), mod:dadobugbedrockores (incompatible), mod:curios, mod:rubidium (incompatible), mod:reeses_sodium_options (incompatible), mod:sodiumextra (incompatible), mod:ftbultimine (incompatible), mod:ftblibrary (incompatible), mod:cucumber (incompatible), mod:infinitywaterbucket (incompatible), mod:ceramicbucket, mod:ceramicshears, mod:bucketlib, mod:woodenbucket, mod:getinthebucketmod, mod:whatthebucket (incompatible), mod:betterfurnacesreforged (incompatible), mod:cobblefordays (incompatible), mod:fpsreducer, mod:compressedblocks, mod:polymorph, mod:projectexpansion (incompatible), mod:constructionwand, mod:hammerlib (incompatible), mod:solarflux (incompatible), mod:create_crystal_clear, mod:extendedflywheels, mod:flywheel (incompatible), mod:create, mod:createsifter (incompatible), mod:worldedit (incompatible), mod:upgradednetherite_items (incompatible), mod:upgradednetherite (incompatible), mod:jeimultiblocks, mod:terrablender, mod:immersiveengineering (incompatible), mod:upgradedcore (incompatible), mod:upgradednetherite_ultimate (incompatible), mod:ultimatefurnaces_bfr (incompatible), mod:mcwlights, mod:mcwpaths, mod:allthecompatibility, mod:shetiphiancore (incompatible), mod:alltheores (incompatible), mod:platforms (incompatible), mod:upgradedtools (incompatible), mod:ironfurnaces (incompatible), mod:mob_grinding_utils (incompatible), mod:betterwithminecolonies, file/minecolonies pathblock datapack.zip, Solar Flux Generated Resources, mod:exmachinis (incompatible), mod:rottenleather (incompatible), mod:buildinggadgets (incompatible), mod:solsweetpotato (incompatible), mod:betteradvancements (incompatible), mod:reliquary (incompatible), mod:compressium (incompatible), mod:mekanism, mod:mekanismgenerators, mod:mekanismadditions, mod:mekanismtools, mod:moremekanismprocessing (incompatible), mod:projecteintegration, mod:ae2 (incompatible), mod:ae2wtlib (incompatible), mod:corail_recycler, mod:fluxnetworks (incompatible), mod:exnihiloae (incompatible), mod:exnihilomekanism, mod:appmek (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: forge-43.1.28
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.1.28.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.1.28.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.1.28.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.1.28.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.1.28.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
		kotlinforforge@3.7.1
	Mod List: 
		BedrockMiner-1.19.x-(v.2.0.0-pre6).jar.jar        |Bedrock Miner                 |bedrockminer                  |2.0.0-pre6          |DONE      |Manifest: NOSIGNATURE
		AllTheCompatibility-1.19.2-(v.1.9.2) .jar         |All The Compatibility         |allthecompatibility           |1.9.2               |DONE      |Manifest: NOSIGNATURE
		HammerLib-1.19.2-19.1.17.jar                      |HammerLib                     |hammerlib                     |19.1.17             |DONE      |Manifest: 97:e8:52:e9:b3:f0:1b:83:57:4e:83:15:f7:e7:76:51:c6:60:5f:2b:45:59:19:a7:31:9e:98:69:56:4f:01:3c
		ProjectE-1.19.2-PE1.0.1B.jar                      |ProjectE                      |projecte                      |1.0.1B              |DONE      |Manifest: NOSIGNATURE
		ProjectExpansion-1.19.2-1.0.1.jar                 |Project Expansion             |projectexpansion              |1.19.2-1.0.1        |DONE      |Manifest: e9:fa:82:d2:7b:66:ce:37:db:52:70:63:25:68:04:a9:72:41:8f:cf:6c:9a:da:52:ab:05:5b:97:2c:13:54:37
		sophisticatedcore-1.19.2-0.5.13.134.jar           |Sophisticated Core            |sophisticatedcore             |1.19.2-0.5.13.134   |DONE      |Manifest: NOSIGNATURE
		rubidium-0.6.2.jar                                |Rubidium                      |rubidium                      |0.6.2               |DONE      |Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.19.2-13.2.3.jar      |CookingForBlockheads          |cookingforblockheads          |13.2.3              |DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.19.2-10.0+6.jar               |Controlling                   |controlling                   |10.0+6              |DONE      |Manifest: NOSIGNATURE
		upgradednetherite_items-1.19.2-4.1.0.1-release.jar|Upgraded Netherite : Items    |upgradednetherite_items       |1.19.2-4.1.0.1-relea|DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19.2-16.1.5.jar                 |Bookshelf                     |bookshelf                     |16.1.5              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.19.2-3.18.29.719.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.19.2-3.18.29.719  |DONE      |Manifest: NOSIGNATURE
		squatgrow-1.0.6-build.26+mc1.19.2.jar             |Squat Grow                    |squatgrow                     |1.0.6-build.26+mc1.1|DONE      |Manifest: NOSIGNATURE
		buildinggadgets-3.16.1-build.15+mc1.19.2.jar      |Building Gadgets              |buildinggadgets               |3.16.1-build.15+mc1.|DONE      |Manifest: NOSIGNATURE
		balm-4.5.3.jar                                    |Balm                          |balm                          |4.5.3               |DONE      |Manifest: NOSIGNATURE
		FpsReducer2-forge-1.19.2-2.1.jar                  |FPS Reducer                   |fpsreducer                    |1.19.2-2.1          |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.19.2-1.1.0.179.jar          |Just Enough Resources         |jeresources                   |1.1.0.179           |DONE      |Manifest: NOSIGNATURE
		cloth-config-8.2.88-forge.jar                     |Cloth Config v8 API           |cloth_config                  |8.2.88              |DONE      |Manifest: NOSIGNATURE
		shetiphiancore-1.19-3.11.0.jar                    |ShetiPhian-Core               |shetiphiancore                |3.11.0              |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.19.2-2.2.3.jar                  |Supplementaries               |supplementaries               |1.19.2-2.2.3        |DONE      |Manifest: NOSIGNATURE
		mob_grinding_utils-1.19.2-0.4.46.jar              |Mob Grinding Utils            |mob_grinding_utils            |1.19.2-0.4.46       |DONE      |Manifest: NOSIGNATURE
		upgradednetherite-1.19.2-5.1.0.2-release.jar      |Upgraded Netherite            |upgradednetherite             |1.19.2-5.1.0.2-relea|DONE      |Manifest: NOSIGNATURE
		alltheores-2.0.0-1.19.2-43.1.3.jar                |AllTheOres                    |alltheores                    |2.0.0-1.19.2-43.1.3 |DONE      |Manifest: NOSIGNATURE
		exmachinis-1.19.2-2.0.1.jar                       |Ex Machinis                   |exmachinis                    |2.0.1               |DONE      |Manifest: NOSIGNATURE
		mcw-bridges-2.0.5-mc1.19.2forge.jar               |Macaw's Bridges               |mcwbridges                    |2.0.5               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.19-1.2.0.jar                     |Farmer's Delight              |farmersdelight                |1.19-1.2.0          |DONE      |Manifest: NOSIGNATURE
		torchmaster-19.2.0.jar                            |Torchmaster                   |torchmaster                   |19.2.0              |DONE      |Manifest: NOSIGNATURE
		Compressium-2.1.1-build.8+mc1.19.jar              |Compressium                   |compressium                   |2.1.1-build.8+mc1.19|DONE      |Manifest: NOSIGNATURE
		ironfurnaces-1.19.2-3.6.3.jar                     |Iron Furnaces                 |ironfurnaces                  |3.6.3               |DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.0.6-mc1.19.2.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.6               |DONE      |Manifest: NOSIGNATURE
		Corail-DT-1.19.2-470.jar                          |Corail Deconstructing Table   |corail_dt                     |1.19.2-470          |DONE      |Manifest: NOSIGNATURE
		ferroustry-1.19-1.0.jar                           |Ferroustry                    |ferroustry                    |4.0                 |DONE      |Manifest: NOSIGNATURE
		upgradedtools-1.19.2-2.1.0.2-release.jar          |Upgraded Tools                |upgradedtools                 |1.19.2-2.1.0.2-relea|DONE      |Manifest: NOSIGNATURE
		textrues_rubidium_options-1.0.3-mc1.19.2.jar      |TexTrue's Rubidium Options    |reeses_sodium_options         |1.0.3-mc1.19.2      |DONE      |Manifest: NOSIGNATURE
		corail_woodcutter_extension_byg-1.19.2-1.0.3.jar  |Corail Woodcutter: Extension B|corail_woodcutter_extension_by|1.0.3               |DONE      |Manifest: NOSIGNATURE
		SolarFluxReborn-1.19.2-19.1.3.jar                 |Solar Flux Reborn             |solarflux                     |19.1.3              |DONE      |Manifest: 97:e8:52:e9:b3:f0:1b:83:57:4e:83:15:f7:e7:76:51:c6:60:5f:2b:45:59:19:a7:31:9e:98:69:56:4f:01:3c
		curios-forge-1.19.2-5.1.1.0.jar                   |Curios API                    |curios                        |1.19.2-5.1.1.0      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.19.2-76.jar                           |Patchouli                     |patchouli                     |1.19.2-76           |DONE      |Manifest: NOSIGNATURE
		corail_woodcutter-1.19.2-2.5.0.jar                |Corail Woodcutter             |corail_woodcutter             |2.5.0               |DONE      |Manifest: NOSIGNATURE
		blockui-1.19-0.0.64-ALPHA.jar                     |UI Library Mod                |blockui                       |1.19-0.0.64-ALPHA   |DONE      |Manifest: NOSIGNATURE
		solsweetpotato-1.19.2-2.0.0.jar                   |Spice of Life: Sweet Potato Ed|solsweetpotato                |1.19.2-2.0.0        |DONE      |Manifest: NOSIGNATURE
		elevatorid-1.19-1.8.7.jar                         |Elevator Mod                  |elevatorid                    |1.19-1.8.7          |DONE      |Manifest: NOSIGNATURE
		ftb-ultimine-forge-1902.3.5-build.65.jar          |FTB Ultimine                  |ftbultimine                   |1902.3.5-build.65   |DONE      |Manifest: NOSIGNATURE
		tombstone-8.1.7-1.19.2.jar                        |Corail Tombstone              |tombstone                     |8.1.7               |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.12.jar                          |WorldEdit                     |worldedit                     |7.2.12+6240-87f4ae1 |DONE      |Manifest: NOSIGNATURE
		ProjectExtended-1.19.2-1.4.0.jar                  |ProjectExtended               |projectextended               |1.4.0               |DONE      |Manifest: NOSIGNATURE
		constructionwand-1.19.1-2.8.jar                   |Construction Wand             |constructionwand              |1.19.1-2.8          |DONE      |Manifest: NOSIGNATURE
		InventoryProfilesNext-forge-1.19-1.8.1.jar        |Inventory Profiles Next       |inventoryprofilesnext         |1.8.1               |DONE      |Manifest: NOSIGNATURE
		pmmo-1.19-0.4.3.jar                               |Project MMO                   |pmmo                          |1.19-0.4.3          |DONE      |Manifest: NOSIGNATURE
		cfm-7.0.0-pre34-1.19.jar                          |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre34         |DONE      |Manifest: NOSIGNATURE
		BetterFurnacesReforged-1.19.2-1.0.2.jar           |BetterFurnaces Reforged       |betterfurnacesreforged        |1.19.2-1.0.2        |DONE      |Manifest: NOSIGNATURE
		architectury-6.2.46-forge.jar                     |Architectury                  |architectury                  |6.2.46              |DONE      |Manifest: NOSIGNATURE
		dadobugbedrockores-1.5.0-forge.jar                |Dadobug1111's Bedrock Ores    |dadobugbedrockores            |1.5.0               |DONE      |Manifest: NOSIGNATURE
		create_crystal_clear-0.1e-1.19.2.jar              |Create: Crystal Clear         |create_crystal_clear          |0.1e                |DONE      |Manifest: NOSIGNATURE
		extendedflywheels-1.2.2-1.19.2-0.5.f.jar          |Extended Flywheels            |extendedflywheels             |1.2.2-1.19.2-0.5.f  |DONE      |Manifest: NOSIGNATURE
		betterwithminecolonies-1.19-1.18.19.jar           |Better With Minecolonies      |betterwithminecolonies        |1.19++-1.18.19      |DONE      |Manifest: NOSIGNATURE
		woodenbucket-1.19-1.1.0.0.jar                     |Wooden Bucket                 |woodenbucket                  |1.19-1.1.0.0        |DONE      |Manifest: NOSIGNATURE
		getinthebucketmod-4.1.2.jar                       |Get in the Bucket Mod         |getinthebucketmod             |4.1.2               |DONE      |Manifest: NOSIGNATURE
		CobbleForDays-1.6.0.jar                           |Cobble For Days               |cobblefordays                 |1.6.0               |DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-30.jar                              |FastLeafDecay                 |fastleafdecay                 |30                  |DONE      |Manifest: NOSIGNATURE
		WhatTheBucket-Forge-1.19.2-7.0.1.jar              |WhatTheBucket                 |whatthebucket                 |7.0.1               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		corail_pillar-5.6.0-1.19.1.jar                    |Corail Pillar                 |corail_pillar                 |5.6.0               |DONE      |Manifest: NOSIGNATURE
		mcw-lights-1.0.4-mc1.19.2.jar                     |Macaw's Lights and Lamps      |mcwlights                     |1.0.4               |DONE      |Manifest: NOSIGNATURE
		Cyclic-1.19.2-1.7.11.jar                          |Cyclic                        |cyclic                        |1.19.2-1.7.11       |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		BetterAdvancements-1.19.2-0.2.2.142.jar           |Better Advancements           |betteradvancements            |0.2.2.142           |DONE      |Manifest: NOSIGNATURE
		BedBenefits-Forge-1.19.2-9.1.2.jar                |BedBenefits                   |bedbenefits                   |9.1.2               |DONE      |Manifest: NOSIGNATURE
		Cucumber-1.19.2-6.0.2.jar                         |Cucumber Library              |cucumber                      |6.0.2               |DONE      |Manifest: NOSIGNATURE
		trashslot-forge-1.19-12.0.0.jar                   |TrashSlot                     |trashslot                     |12.0.0              |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-1902.3.9-build.144.jar          |FTB Library                   |ftblibrary                    |1902.3.9-build.144  |DONE      |Manifest: NOSIGNATURE
		platforms-1.19-1.10.0.jar                         |Platforms                     |platforms                     |1.10.0              |DONE      |Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.3.0.262.jar                   |Just Enough Items             |jei                           |11.3.0.262          |DONE      |Manifest: NOSIGNATURE
		AttributeFix-Forge-1.19.2-17.1.2.jar              |AttributeFix                  |attributefix                  |17.1.2              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		RottenLeather-1.19-1.4.jar                        |Rotten Leather                |rottenleather                 |1.4                 |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.19.2-10.3.4.471.jar                    |Mekanism                      |mekanism                      |10.3.4              |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.19.2-10.3.4.471.jar          |Mekanism: Generators          |mekanismgenerators            |10.3.4              |DONE      |Manifest: NOSIGNATURE
		MekanismAdditions-1.19.2-10.3.4.471.jar           |Mekanism: Additions           |mekanismadditions             |10.3.4              |DONE      |Manifest: NOSIGNATURE
		MekanismTools-1.19.2-10.3.4.471.jar               |Mekanism: Tools               |mekanismtools                 |10.3.4              |DONE      |Manifest: NOSIGNATURE
		MoreMekanismProcessing-1.19.2-3.0.jar             |More Mekanism Processing      |moremekanismprocessing        |3.0                 |DONE      |Manifest: NOSIGNATURE
		Infinity-Water-Bucket-1.19-2.0.0.jar              |Infinity Water Bucket         |infinitywaterbucket           |2.0.0               |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.19.2-9.0.0+11.jar                  |Clumps                        |clumps                        |9.0.0+11            |DONE      |Manifest: NOSIGNATURE
		journeymap-1.19.1-5.9.0beta2-forge.jar            |Journeymap                    |journeymap                    |5.9.0beta2          |DONE      |Manifest: NOSIGNATURE
		comforts-forge-6.0.2+1.19.2.jar                   |Comforts                      |comforts                      |6.0.2+1.19.2        |DONE      |Manifest: NOSIGNATURE
		configured-2.0.1-1.19.2.jar                       |Configured                    |configured                    |2.0.1               |DONE      |Manifest: NOSIGNATURE
		farmingforblockheads-forge-1.19-11.1.0.jar        |Farming for Blockheads        |farmingforblockheads          |11.1.0              |DONE      |Manifest: NOSIGNATURE
		bedspreads-forge-6.0.0+1.19.2.jar                 |Bedspreads                    |bedspreads                    |6.0.0+1.19.2        |DONE      |Manifest: NOSIGNATURE
		projecte-integration-1.19.2-6.0.3.jar             |ProjectE Integration          |projecteintegration           |6.0.3               |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.1.28-universal.jar                |Forge                         |forge                         |43.1.28             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		jeimultiblocks-1.19.2-0.0.3.jar                   |Just Enough Immersive Multiblo|jeimultiblocks                |0.0.3               |DONE      |Manifest: NOSIGNATURE
		mcw-paths-1.0.1-mc1.19.2.jar                      |Macaw's Paths and Pavings     |mcwpaths                      |1.0.1               |DONE      |Manifest: NOSIGNATURE
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		compressedblocks_1.19.2-d8c7bb9-1.1.0-20220930.jar|CB: Compressed Blocks         |compressedblocks              |1.1.0-20220930      |DONE      |Manifest: NOSIGNATURE
		libIPN-forge-1.19-1.0.1.jar                       |Inventory Profiles Next       |libipn                        |1.0.1               |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.19.2-13.0.3.jar   |EnchantmentDescriptions       |enchdesc                      |13.0.3              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TerraBlender-forge-1.19.2-2.0.1.127.jar           |TerraBlender                  |terrablender                  |2.0.1.127           |DONE      |Manifest: NOSIGNATURE
		swingthroughgrass-1.19.2-1.10.0.jar               |SwingThroughGrass             |swingthroughgrass             |1.19.2-1.10.0       |DONE      |Manifest: NOSIGNATURE
		moonlight-1.19.2-2.0.32.jar                       |Moonlight Library             |moonlight                     |1.19.2-2.0.32       |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.19-2.23.jar                 |Mouse Tweaks                  |mousetweaks                   |2.23                |DONE      |Manifest: NOSIGNATURE
		titanium-1.19.2-3.7.0-23.jar                      |Titanium                      |titanium                      |3.7.0               |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.19.2-9.0.0-153.jar         |Immersive Engineering         |immersiveengineering          |1.19.2-9.0.0-153    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		EasierSleeping-1.19.2-2.1.2.jar                   |Easier Sleeping               |easier_sleeping               |2.1.2               |DONE      |Manifest: NOSIGNATURE
		Jade-1.19.1-forge-8.3.0.jar                       |Jade                          |jade                          |8.3.0               |DONE      |Manifest: NOSIGNATURE
		appliedenergistics2-12.7.0.jar                    |Applied Energistics 2         |ae2                           |12.7.0              |DONE      |Manifest: NOSIGNATURE
		AE2WTLib-12.7.0.jar                               |AE2WTLib                      |ae2wtlib                      |12.7.0              |DONE      |Manifest: NOSIGNATURE
		ceramicbucket-1.19-3.1.0.0.jar                    |Ceramic Bucket                |ceramicbucket                 |1.19-3.1.0.0        |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.10.0+1.19.jar                  |SpectreLib                    |spectrelib                    |0.10.0+1.19         |DONE      |Manifest: NOSIGNATURE
		domum_ornamentum-1.19-1.0.60-ALPHA-universal.jar  |Domum Ornamentum              |domum_ornamentum              |1.19-1.0.60-ALPHA   |DONE      |Manifest: NOSIGNATURE
		ceramicshears-1.19-1.7.0.0.jar                    |Ceramic Shears                |ceramicshears                 |1.19-1.7.0.0        |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.19.2-0.6.7-8.jar                 |Flywheel                      |flywheel                      |0.6.7-8             |DONE      |Manifest: NOSIGNATURE
		create-1.19.2-0.5.0.f.jar                         |Create                        |create                        |0.5.0.f             |DONE      |Manifest: NOSIGNATURE
		createsifter-1.19.2-1.2.3.f.jar                   |Create Sifter                 |createsifter                  |1.19.2-1.2.3.f      |DONE      |Manifest: NOSIGNATURE
		reliquary-1.19.2-2.0.20.1166.jar                  |Reliquary                     |reliquary                     |1.19.2-2.0.20.1166  |DONE      |Manifest: NOSIGNATURE
		bucketlib-1.19-1.0.3.2.jar                        |BucketLib                     |bucketlib                     |1.19-1.0.3.2        |DONE      |Manifest: NOSIGNATURE
		RubidiumExtra-1.19.2-0.4.10.35.jar                |Rubidium Extra                |sodiumextra                   |1.19.2-0.4.10.35    |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.19.2-FORGE-2.1.0.jar                  |Croptopia                     |croptopia                     |2.1.0               |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-0.45.0+1.19.2.jar                 |Polymorph                     |polymorph                     |0.45.0+1.19.2       |DONE      |Manifest: NOSIGNATURE
		corail_recycler-5.6.0-1.19.jar                    |Corail Recycler               |corail_recycler               |5.6.0               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.8-54.jar                             |AutoRegLib                    |autoreglib                    |1.8-54              |DONE      |Manifest: NOSIGNATURE
		Quark-3.3-371.jar                                 |Quark                         |quark                         |3.3-371             |DONE      |Manifest: NOSIGNATURE
		FluxNetworks-1.19.2-7.1.1.10.jar                  |Flux Networks                 |fluxnetworks                  |7.1.1.10            |DONE      |Manifest: NOSIGNATURE
		InventoryHud_[1.19.2].forge-3.4.6.jar             |Inventory HUD+(Forge edition) |inventoryhud                  |3.4.6               |DONE      |Manifest: NOSIGNATURE
		structurize-1.19.2-1.0.452-ALPHA.jar              |Structurize                   |structurize                   |1.19.2-1.0.452-ALPHA|DONE      |Manifest: NOSIGNATURE
		multi-piston-1.19-1.2.16-ALPHA.jar                |Multi-Piston                  |multipiston                   |1.19-1.2.16-ALPHA   |DONE      |Manifest: NOSIGNATURE
		upgradedcore-1.19.2-4.1.0.0-release.jar           |Upgraded Core                 |upgradedcore                  |1.19.2-4.1.0.0-relea|DONE      |Manifest: NOSIGNATURE
		minecolonies-1.19.2-1.0.1062-ALPHA.jar            |MineColonies                  |minecolonies                  |1.19.2-1.0.1062-ALPH|DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |DONE      |Manifest: NOSIGNATURE
		upgradednetherite_ultimate-1.19.2-4.1.0.0-release.|Upgraded Netherite : Ultimerit|upgradednetherite_ultimate    |1.19.2-4.1.0.0-relea|DONE      |Manifest: NOSIGNATURE
		functionalstorage-1.19.2-1.0.6.jar                |Functional Storage            |functionalstorage             |1.19.2-1.0.6        |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.19.2-2.4.7.jar                      |Aquaculture 2                 |aquaculture                   |1.19.2-2.4.7        |DONE      |Manifest: NOSIGNATURE
		Corail-Backpack-1.19.2-155.jar                    |Corail Backpack               |corail_backpack               |1.19.2-155          |DONE      |Manifest: NOSIGNATURE
		UltimateFurnaces-1.19.2-1.0.1.jar                 |Ultimate Furnaces             |ultimatefurnaces_bfr          |1.0.1               |DONE      |Manifest: NOSIGNATURE
		ExNihiloSequentia-1.19.2-4.0.0.43-beta.jar        |Ex Nihilo: Sequentia          |exnihilosequentia             |1.19.2-4.0.0.43-beta|DONE      |Manifest: NOSIGNATURE
		ExNihiloAE-1.19.2-4.0.0.42-beta.jar               |Ex Nihilo: Sequentia - AE2 Add|exnihiloae                    |1.19.2-4.0.0.42-beta|DONE      |Manifest: NOSIGNATURE
		ExNihiloMekanism-1.19.2-4.0.0.43-beta.jar         |Ex Nihilo: Sequentia - Mekanis|exnihilomekanism              |1.19.2-4.0.0.43-beta|DONE      |Manifest: NOSIGNATURE
		Applied-Mekanistics-1.3.2.jar                     |Applied Mekanistics           |appmek                        |1.3.2               |DONE      |Manifest: NOSIGNATURE
		xptome-1.19-2.1.6.jar                             |XP Tome                       |xpbook                        |2.1.6               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 38eb7729-b396-411b-acec-1b252f65fa5e
	Flywheel Backend: GL33 Instanced Arrays
	FML: 43.1
	Forge: net.minecraftforge:43.1.28

**Comment by adamkad1** [comment]
Is that the right log anyway...

**Comment by Wilyicaro** [comment]
Hi, sorry for the inconvenience again, in my testing of this bug at the time I wasn't getting this bug so I believed I had fixed it. Well, I've just found a definitive solution, but I'll test it first with the mod you used for upgrade compatibility (Cyclic, I guess).
I believe the incompatible mods are due to the older version of forge these mods used.

**Comment by adamkad1** [comment]
I tried with MGU fluid first but it also crashed with cyclic.

**Comment by Wilyicaro** [comment]
I've already fixed this bug definitely, I'll post the fix soon, again, sorry for the inconvenience and thanks for reporting it

**Comment by Wilyicaro** [comment]
Certainly fixed in version 1.19.2-1.0.3

**Comment by Wilyicaro** [comment]
Could you test for me if the fix really worked in your tests?

**Comment by adamkad1** [comment]
> 

Oh man I forgot to check up here.

It still crashes with ultimate forge. Extreme forge however, works normally.

**Comment by Wilyicaro** [comment]
Very strange, Ultimate Furnaces forges are entirely based on the base mod's Extreme forge, perhaps this Ultimate Forge was put in before the bug was supposedly fixed

**Comment by adamkad1** [comment]
> Very strange, Ultimate Furnaces forges are entirely based on the base mod's Extreme forge, perhaps this Ultimate Forge was put in before the bug was supposedly fixed

Nah, checked it the same day I posted that error.

**Comment by Wilyicaro** [comment]
The strangest thing is that I can't find this crash anymore under the same conditions as you, try to see if this doesn't happen with the furnaces and extreme forge of BFR
